name: json_de_serialisation
description: Example showing JSON serialisation and deserialisation for abstract data
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  equatable: 2.0.5
  json_annotation: 4.7.0
  json_serializable: 6.5.4

dev_dependencies:
  build_runner: 2.3.2
  lints: ^2.0.0
  test: ^1.16.0
